// Public, reviewed product guidance. Never put private account data or credentials here.
// Update the version whenever policy or product behaviour changes.
export const SUPPORT_KNOWLEDGE_VERSION = '2026-09-14.1';
export type SupportLocale = 'ko' | 'en';
type Copy = Record<SupportLocale, string>;
export type SupportCategory = 'start' | 'account' | 'profile' | 'projects' | 'ai' | 'notifications' | 'policy';
export interface SupportArticle {
    id: string;
    category: SupportCategory;
    title: Copy;
    answer: Copy;
    keywords: string[];
}
const copy = (ko: string, en: string): Copy => ({ ko, en });
const article = (id: string, category: SupportCategory, title: Copy, answer: Copy, terms: string): SupportArticle => ({ id, category, title, answer, keywords: terms.split('|') });
export const SUPPORT_CATEGORIES: Record<SupportCategory, Copy> = {
    start: copy('처음 이용하기', 'Getting started'),
    account: copy('가입·로그인', 'Account & sign-in'),
    profile: copy('프로필·서류', 'Profile & documents'),
    projects: copy('공고·프로젝트', 'Jobs & projects'),
    ai: copy('AI·평가', 'AI & assessments'),
    notifications: copy('알림·이메일', 'Notifications & email'),
    policy: copy('이용정책·지원', 'Policies & support'),
};
export const SUPPORT_ARTICLES: SupportArticle[] = [
    article('what-is-konexa', 'start', copy('KONEXA는 어떤 서비스인가요?', 'What is KONEXA?'), copy('한국 기업과 글로벌 인재가 실제 프로젝트로 함께 일하며 서로의 역량과 협업 방식을 확인하는 플랫폼입니다. 기업은 업무 범위와 주차별 결과물을 정하고, 인재는 프로필을 완성한 뒤 공고에 지원합니다.\n\n채용이나 특정 성과가 자동으로 보장되는 서비스는 아닙니다. 현재 모집·진행 가능 여부는 실제 공고와 운영팀 안내를 기준으로 확인해 주세요.', 'KONEXA connects Korean companies and global talent through real projects, so both sides can assess skills and how they work together. Companies define the scope and weekly deliverables; talent complete a profile and apply to published opportunities.\n\nHiring and specific outcomes are not guaranteed. Check live listings and the operations team for current availability.'), '코넥사|konexa|어떤 서비스|플랫폼 소개|what is|là gì'),
    article('company-start', 'start', copy('기업은 어떻게 시작하나요?', 'How does a company get started?'), copy('기업 계정 가입 → 필수 회사 정보와 사업자 서류 등록 → 운영팀 인증 → 실제 공고 등록 순서로 진행합니다. 공고에는 업무 범위, 요구 역량, 기간, 주차별 결과물을 구체적으로 적어 주세요.\n\n계정을 만들거나 서류를 제출했다고 인증이 자동 승인되지는 않습니다. AI 인재 매칭 등 인증이 필요한 기능은 승인 후 사용할 수 있습니다.', 'Create a company account, complete the required company details and business documents, obtain verification, then publish a real opportunity. Describe the scope, required skills, duration and weekly deliverables.\n\nSubmitting documents does not automatically approve your company. Verification-gated features, including AI talent matching, become available after approval.'), '기업 시작|회사 가입|company start|employer|doanh nghiệp bắt đầu'),
    article('talent-start', 'start', copy('학생·인재는 어떻게 참여하나요?', 'How can talent participate?'), copy('학생 계정으로 가입하고 필수 프로필·재학 증빙·PDF 이력서를 등록하세요. 관심 직무와 기술을 선택한 뒤 실제 공고를 확인하고 지원할 수 있습니다. 자기소개 영상은 마이페이지에서 추가합니다.\n\n학교 이름만으로 검증이나 선발이 보장되지는 않습니다. 공고별 요구 역량과 참여 가능 시간을 확인해 주세요.', 'Create a student account and complete your profile, academic proof and PDF resume. Select your roles and skills, then browse and apply to real opportunities. You can add an introduction video from your profile.\n\nA university name alone does not guarantee verification or selection. Check each project’s requirements and time commitment.'), '학생 시작|인재 참여|student start|talent join|sinh viên tham gia'),
    article('signup', 'account', copy('회원가입 절차가 궁금해요', 'How do I sign up?'), copy('가입 화면에서 학생 또는 기업을 선택하세요. 이메일·비밀번호 또는 Google로 시작한 뒤 필수 동의를 완료합니다. 이메일 가입은 인증 메일 확인이 필요할 수 있습니다.\n\n계정 생성과 프로필 완성은 별도 단계입니다. 가입 후 표시되는 필수정보 화면을 저장해야 대시보드를 이용할 수 있습니다.', 'Choose student or company on the sign-up screen. Start with email and password or Google, then complete the required consent steps. Email sign-up may require email confirmation.\n\nCreating an account and completing a profile are separate steps. Save the required profile details shown after sign-up to access the dashboard.'), '회원가입|가입 방법|sign up|signup|register|đăng ký'),
    article('google-login', 'account', copy('Google로 시작할 수 없어요', 'Google sign-in is not working'), copy('konexa.co.kr에서 Google로 시작하기를 선택하고 사용할 계정을 확인해 주세요. 처음 이용하면 역할 선택과 필수 동의 화면이 이어집니다. 이 단계를 마쳐야 일반 회원 기능이 열립니다.\n\n창이 차단되면 브라우저의 팝업·리디렉션 허용 여부를 확인하고 다시 시도하세요. 반복되면 발생 시각과 오류 문구를 운영팀에 보내 주세요. 비밀번호나 인증코드는 보내지 마세요.', 'Use Continue with Google on konexa.co.kr and select your account. First-time users then choose a role and complete the required consent steps before accessing member features.\n\nIf the browser blocks the flow, check its pop-up and redirect settings and retry. If it repeats, send support the time and error text—not your password or verification code.'), '구글|google|oauth|popup|팝업'),
    article('email-confirmation', 'account', copy('가입 인증 메일이 오지 않아요', 'My confirmation email has not arrived'), copy('입력한 주소와 스팸·프로모션함을 확인해 주세요. 인증 메일을 여러 번 요청했다면 가장 최근 메일의 링크를 사용하세요. 재전송 버튼이 있는 경우 잠시 기다린 뒤 한 번만 요청하세요.\n\n계속 수신되지 않으면 가입 이메일과 요청 시각을 운영팀에 알려 주세요. 챗봇은 메일 수신함을 확인하거나 계정을 직접 인증할 수 없습니다.', 'Check the address you entered and your spam or promotions folder. If you requested several emails, use the newest link. Where a resend button is available, wait briefly and request once.\n\nIf nothing arrives, contact support with your sign-up email and request time. This chatbot cannot inspect your inbox or verify your account for you.'), '인증 메일|인증메일|confirmation|verification email|메일 안|email xác nhận'),
    article('session', 'account', copy('세션 만료·로그인 반복 오류가 나요', 'My session expired or sign-in keeps repeating'), copy('먼저 같은 도메인인 https://konexa.co.kr에서 새로고침해 보세요. 과거 chatgpt.site 주소나 다른 배포 주소에서는 로그인 상태가 공유되지 않을 수 있습니다.\n\n계속되면 작성 중인 내용을 따로 보관한 뒤 로그아웃하고 다시 로그인하세요. 프로필 작성 화면으로 이동하는 것은 계정 삭제가 아니라 필수정보 확인 단계일 수 있습니다. 오류가 반복되면 운영팀에 알려 주세요.', 'First refresh https://konexa.co.kr. Sessions may not be shared with old chatgpt.site addresses or other deployment domains.\n\nIf the problem continues, keep a copy of any unsaved work, sign out and sign in again. Being sent to profile setup can mean required details are incomplete, not that your account was deleted. Contact support if the error persists.'), '세션|로그아웃|session|signed out|expired|로그인 반복|phiên|hết hạn'),
    article('password', 'account', copy('비밀번호를 잊었어요', 'I forgot my password'), copy('로그인 화면의 비밀번호 재설정을 이용하세요. 가입한 이메일을 입력하고 받은 링크에서 새 비밀번호를 설정합니다. Google로만 가입했다면 먼저 Google 로그인을 이용해 주세요.\n\n운영팀과 챗봇은 현재 비밀번호를 알려주거나 대신 정해 드리지 않습니다.', 'Use password reset on the sign-in screen, enter your registered email and follow the link to set a new password. If you joined only through Google, try Google sign-in first.\n\nNeither support nor this chatbot can reveal your current password or choose one for you.'), '비밀번호|password|mật khẩu'),
    article('student-profile', 'profile', copy('학생 필수정보는 무엇인가요?', 'What must a student profile include?'), copy('이름, 국적·거주국·시간대, 학교·학위·전공·졸업연도, 영어 수준, 보유 기술, 희망 직무, 시작 가능 시점, 희망 주급, 자기소개가 필요합니다. 재학증명서 또는 학생증과 PDF 이력서도 업로드해야 합니다.\n\nGitHub나 공개 포트폴리오는 필수가 아닙니다. 개발 외 직무도 참여할 수 있으며, 실제로 보유한 역량만 적어 주세요.', 'Provide your name, nationality, country, time zone, university, degree, major, graduation year, English level, skills, preferred roles, availability, weekly pay preference and introduction. Upload academic proof or a student ID and a PDF resume.\n\nGitHub and a public portfolio are optional. Non-software roles are welcome; list only skills you actually have.'), '학생 필수|student profile|required student|hồ sơ sinh viên'),
    article('company-profile', 'profile', copy('기업 필수정보·서류는 무엇인가요?', 'What company details and documents are required?'), copy('사업체명·사업자등록번호·국가·업종·규모·웹사이트·사업장 소재지, 담당자 이름·직책·이메일·전화번호, 회사 소개와 필요 기술을 등록합니다. 사업자등록증 업로드도 필수입니다.\n\n해외 기업 등 국내 사업자등록증과 다른 서류를 사용하는 경우 운영팀에 적합한 증빙을 먼저 문의해 주세요. 챗봇이 서류 적합성이나 승인을 대신 판단하지는 않습니다.', 'Enter the business name, registration number, country, industry, size, website, location, contact person, job title, email and phone, plus a company introduction and required skills. A business registration document is also required.\n\nIf your company uses different documentation, such as an overseas registration, ask operations which evidence is appropriate. This chatbot cannot approve documents.'), '기업 필수|사업자등록증|사업자등록번호|company document|business registration|giấy kinh doanh'),
    article('upload', 'profile', copy('파일 업로드·프로필 저장에 실패해요', 'A file upload or profile save failed'), copy('필수항목을 모두 작성하고 업로드 화면에 표시된 파일 형식·용량 제한을 확인하세요. 이력서는 PDF를 사용합니다. 업로드가 끝나기 전에 화면을 닫지 마세요.\n\n필수 서류가 저장소에서 확인되지 않는다는 안내가 나오면 서류 단계에서 다시 업로드한 후 저장하세요. 문제가 계속되면 오류 문구와 발생 시각만 지원팀에 보내 주세요. 민감한 서류를 챗봇에 올리지 마세요.', 'Complete every required field and check the format and size limits shown by the upload control. Resumes must be PDF. Keep the page open until the upload finishes.\n\nIf a required document cannot be found in storage, upload it again in the documents step and save. If the problem persists, send support the error text and time. Do not put sensitive documents in the chatbot.'), '업로드|저장 실패|저장 안|rls|row-level|upload|save failed|tải tệp|lưu hồ sơ'),
    article('verification', 'profile', copy('서류 제출 후 언제 승인되나요?', 'When will my documents be approved?'), copy('서류 제출 후에는 검토 대기 상태가 됩니다. 운영팀이 증빙을 확인하고 승인 또는 보완 요청을 처리합니다. 정확한 처리 시간은 현재 검토량에 따라 달라서 챗봇이 확정할 수 없습니다.\n\nAI 분석 완료와 본인·기업 인증 승인은 서로 다릅니다. 마이페이지의 실제 인증 상태와 알림을 확인해 주세요. 이 챗봇은 개인 계정의 승인 상태를 조회하지 않습니다.', 'After submission, documents enter review. Operations checks the evidence and either approves it or requests changes. Timing depends on the review queue; this chatbot cannot promise a deadline.\n\nAn AI analysis is not identity or business verification. Check your profile’s actual verification status and notifications. This chatbot does not look up private account status.'), '승인|검토 대기|인증 상태|verified|approval|verification status|duyệt|xác minh'),
    article('video', 'profile', copy('1분 자기소개 영상은 어떻게 사용되나요?', 'How is my one-minute introduction video used?'), copy('학생 마이페이지에서 자기소개 영상을 업로드·관리합니다. 본인의 역할, 잘하는 일, 참여 가능한 시간을 짧게 소개하세요. 구체적인 파일 제한은 업로드 화면에 표시됩니다.\n\n영상은 공개 랜딩페이지에 무조건 노출되지 않습니다. 본인·관리자와 지원이 승인되어 매칭된 기업 등 권한이 있는 이용자에게만 제한된 링크로 제공됩니다.', 'Upload and manage your introduction video from the student profile. Briefly describe your role, strengths and availability. The upload screen shows the file limits.\n\nVideos are not automatically public on the landing page. Access is restricted to you, administrators and an authorized company after an application is approved, using a temporary link.'), '영상|비디오|video|introduction video'),
    article('weekly-pay', 'profile', copy('희망 급여는 주급으로 입력하나요?', 'Should I enter weekly pay?'), copy('네. 학생 프로필에는 연봉이나 월급이 아니라 원화 기준 희망 주급을 입력합니다. 금액 예시는 제공하지 않으며, 가능한 업무 시간과 본인의 역량을 고려해 입력하세요.\n\n프로필의 희망 금액은 확정 지급액이 아닙니다. 실제 지급 조건·통화·수수료는 해당 프로젝트의 확정 안내를 확인해야 합니다.', 'Yes. Enter your preferred weekly amount in Korean won, not annual or monthly salary. No suggested amount is supplied; consider your availability and skills.\n\nA profile preference is not a confirmed payout. Check the final project terms for the actual amount, currency and any fees.'), '주급|salary|weekly pay|월급|연봉|thù lao|lương'),
    article('roles', 'profile', copy('개발자가 아니어도 참여할 수 있나요?', 'Can I join for a non-software role?'), copy('네. 개발·소프트웨어 외에도 디자인, 마케팅, 콘텐츠, 리서치, 비즈니스 등 다양한 직무를 선택할 수 있습니다. 관심 직무와 보유 기술은 복수 선택하고 필요한 경우 직접 추가하세요.\n\n직무를 선택했다고 한국 취업비자 자격이 인정되는 것은 아닙니다. 실제 모집 여부는 게시된 공고를 기준으로 확인합니다.', 'Yes. Roles extend beyond software to design, marketing, content, research, business and other fields. Select multiple roles and skills, or add an option when supported.\n\nSelecting a role does not establish Korean work-visa eligibility. Check published listings for roles currently available.'), '직무|직종|복수 선택|개발자|non-software|roles|designer|marketing|ngành nghề'),
    article('public-jobs', 'projects', copy('로그인 전에 공고를 볼 수 있나요?', 'Can I preview opportunities before signing in?'), copy('랜딩페이지에서 기업이 실제로 공개한 공고 일부를 미리 볼 수 있습니다. 자세한 내용 확인과 지원은 가입·로그인 후 진행합니다.\n\n공개 공고가 없을 때는 빈 상태를 표시합니다. 예시 기업이나 가짜 채용 공고를 실제 모집처럼 표시하지 않습니다.', 'The landing page previews opportunities companies have actually published. Sign up or sign in to continue to full details and applications.\n\nIf no public opportunities are available, the page shows an empty state—not sample employers presented as real openings.'), '공고 없어|공고 보기|로그인 전|public jobs|browse jobs|no jobs|xem việc'),
    article('post-job', 'projects', copy('기업 공고에는 무엇을 적어야 하나요?', 'What should a company put in a listing?'), copy('기업 대시보드의 공고 등록 양식을 이용하세요. 제목, 실제 업무, 필요한 기술·언어, 기간·주당 시간, 주차별 결과물을 명확히 작성합니다. 지원 마감과 근무 방식도 실제 조건에 맞춰 주세요.\n\n정상 등록된 공개 공고는 학생 공고 화면과 공개 미리보기에 반영됩니다. 연락처를 본문에 넣어 계약 전 직접 접촉을 유도하지 마세요.', 'Use the company dashboard’s listing form. State the title, work, skills, language requirements, duration, weekly hours and weekly deliverables. Set an accurate deadline and work arrangement.\n\nSuccessfully published listings appear in student opportunities and public previews. Do not put contact details in the description to bypass the pre-contract contact process.'), '공고 등록|구인공고|jd|post job|job description|publish|đăng tin'),
    article('apply', 'projects', copy('지원 후에는 어떻게 진행되나요?', 'What happens after I apply?'), copy('공고의 조건을 확인하고 지원 내용을 제출하세요. 지원 내역에서 실제 처리 상태를 확인할 수 있고, 기업의 검토·상태 변경은 알림으로 안내됩니다. 제출 실패 안내가 있으면 지원 완료로 간주하지 마세요.\n\n선발이나 답변 시점을 보장하지는 않습니다. 문제가 있으면 공고명과 지원 시각을 운영팀에 알려 주세요.', 'Check the listing’s requirements and submit your application. Track the actual state in your applications; review and status changes generate notifications. A failed submission is not a completed application.\n\nSelection and response times are not guaranteed. If there is a problem, send operations the listing title and submission time.'), '지원|application|apply|ứng tuyển'),
    article('scope', 'projects', copy('업무 범위와 주차별 결과물은 어떻게 관리하나요?', 'How are scope and weekly deliverables managed?'), copy('착수 전에 포함·제외 업무, 예상 시간, 검수 기준, 제출물과 기한을 먼저 정합니다. 진행 중에는 프로젝트의 마일스톤과 제출 기록으로 확인합니다.\n\n추가 업무나 일정 변경은 기록을 남기고 양측이 확인한 뒤 진행하세요. 챗봇은 계약을 체결하거나 범위를 임의로 변경하지 않습니다.', 'Before starting, agree on included and excluded work, expected hours, acceptance criteria, deliverables and deadlines. Track progress through project milestones and submission records.\n\nRecord and confirm additional work or schedule changes with both sides before proceeding. This chatbot cannot sign contracts or change scope.'), '범위|마일스톤|결과물|scope|milestone|deliverable|phạm vi|bàn giao'),
    article('matching', 'ai', copy('AI 매칭은 어떤 기준인가요?', 'How does AI matching work?'), copy('인증된 기업이 자기 공고를 선택하면 공고의 요구사항과 실제 익명 인재 카드의 기술·언어·경험 정보를 비교합니다. 결과에는 적합도, 근거, 부족한 정보, 면접 질문 등이 포함될 수 있습니다.\n\n적합도는 참고용 추정치이며 채용 확률이나 실력 인증서가 아닙니다. 없는 인재를 만들어 추천하지 않으며 최종 판단은 사람이 해야 합니다.', 'A verified company selects its own listing. AI compares the requirements with real anonymized talent cards, including skills, languages and experience. Results may include suitability, supporting factors, missing evidence and interview questions.\n\nSuitability is advisory, not a hiring probability or certified skill level. No candidates should be invented; humans make the final decision.'), '매칭|matching|suitability|ghép|phù hợp'),
    article('ai-analysis', 'ai', copy('AI 분석·점수는 무엇을 의미하나요?', 'What do AI analysis and scores mean?'), copy('저장된 프로필이나 제출 근거를 바탕으로 강점, 보완점, 학습 방향 등을 제안합니다. AI 점수는 입력 정보에 따른 참고 의견이며 검증된 경력·취업 가능성·비자 승인을 보장하지 않습니다.\n\nAI 분석이 지연되거나 실패해도 정상 저장된 프로필이 사라지는 것은 아닙니다. 프로필 상태를 확인한 뒤 AI 기능에서 다시 시도하고, 사실과 다른 결과는 운영팀에 알려 주세요.', 'AI uses saved profile details or submitted evidence to suggest strengths, improvements and learning steps. Scores are advisory opinions based on that input—not guarantees of verified experience, employment or visa approval.\n\nA delayed or failed analysis does not erase a successfully saved profile. Check the profile, retry the AI feature and report factual mistakes to operations.'), 'ai 분석|ai 스코어|ai 점수|analysis|score|ai 오류|phân tích|điểm ai'),
    article('ai-coach', 'ai', copy('AI 코치와 도움말 챗봇은 다른가요?', 'How is an AI coach different from this help chatbot?'), copy('이 도움말 챗봇은 가입·공고·이용정책 같은 사이트 이용법을 안내합니다. 개인 계정이나 지원 상태를 조회·변경하지 않습니다.\n\n로그인 후 AI 코치는 진로, 이력서 표현, 면접, 프로젝트 계획 등을 도와줍니다. 코치에 보내는 정보는 AI 서비스에서 처리되므로 비밀번호, 신분증 번호, 고객정보, 영업비밀을 입력하지 마세요.', 'This help chatbot explains sign-up, listings and product policies. It cannot inspect or change private accounts or applications.\n\nAfter sign-in, AI coaches help with careers, resume wording, interviews and project planning. Content you send is processed by the AI service, so never enter passwords, identity numbers, customer data or trade secrets.'), '코치|챗봇|coach|chatbot|상담|huấn luyện'),
    article('ai-unavailable', 'ai', copy('AI가 응답하지 않거나 오래 걸려요', 'AI is slow or not responding'), copy('AI 공급자 혼잡, 요청 제한, 네트워크 문제로 지연될 수 있습니다. 전송 중에는 중복 클릭하지 말고, 실패 안내가 나오면 잠시 후 다시 시도하세요.\n\n도움말의 주제 버튼은 AI가 없어도 확인된 답변을 보여줍니다. 오류가 계속되면 사용한 기능과 발생 시각을 알려 주세요. 정상 응답을 받지 못한 작업을 완료됐다고 안내하지 않습니다.', 'Provider congestion, rate limits or network issues can delay AI. Avoid repeated clicks while sending; retry after a short wait if an error appears.\n\nThe help topic buttons still show reviewed answers without AI. If errors continue, tell support which feature and when. A failed AI request is not a completed task.'), 'ai 안|ai 응답|ai 느|ai slow|not responding|ai unavailable|ai chậm'),
    article('notifications', 'notifications', copy('어떤 알림이 오고 어디서 확인하나요?', 'Where can I see notifications?'), copy('로그인 후 상단 종 모양에서 계정에 저장된 알림을 확인합니다. 지원 접수·상태 변경, 공고, 인증, 소개 요청, 계약·마일스톤·리뷰·분쟁 등 실제 이벤트에 따라 알림이 생성됩니다.\n\n알림을 누르면 읽음으로 저장하고 관련 화면으로 이동합니다. 이메일 알림은 별도 전달 과정과 수신 설정을 따르므로 사이트 알림과 도착 시각이 다를 수 있습니다.', 'After signing in, open the bell in the top navigation. Notifications are stored for your account and created by real events such as applications, listing updates, verification, introductions, contracts, milestones, reviews and disputes.\n\nOpening a notification saves it as read and takes you to the relevant screen. Email delivery is separate and follows your preferences, so arrival times can differ.'), '알림|notification|종 모양|읽음|thông báo'),
    article('email-notifications', 'notifications', copy('이메일 알림이 오지 않아요', 'Why am I not receiving notification emails?'), copy('계정의 이메일 알림 수신 설정, 가입 이메일, 스팸함을 확인하세요. 이메일을 꺼 두어도 사이트 알림은 별도로 확인할 수 있습니다. 인증·비밀번호 메일은 일반 업무 알림과 다른 경로로 처리됩니다.\n\n메일 전송 요청, 공급자 접수, 실제 받은편지함 도착은 서로 다른 단계입니다. 챗봇은 받은편지함 도착을 보장하지 않습니다. 누락이 의심되면 관련 작업과 발생 시각을 운영팀에 보내 주세요.', 'Check your email notification preferences, registered address and spam folder. In-app notifications remain separate when email is disabled. Confirmation and password emails use a different flow from workflow notifications.\n\nRequesting a send, provider acceptance and inbox delivery are different stages. This chatbot cannot guarantee inbox delivery. Report the relevant action and time if an email appears missing.'), '이메일 알림|email notification|email preference|메일 수신|email thông báo'),
    article('reviews', 'projects', copy('서로 리뷰를 작성할 수 있나요?', 'Can both sides leave a review?'), copy('실제 거래·프로젝트와 연결된 리뷰 절차를 사용합니다. 공개 전 상대방의 비공개 리뷰가 노출되지 않도록 구분하며, 단순 가입만으로 가짜 거래 리뷰를 만들 수는 없습니다.\n\n사실과 의견을 구분해 작성하고 개인정보·차별 표현·보복성 내용을 넣지 마세요. 이의가 있으면 관련 프로젝트와 문제 내용을 운영팀에 전달해 주세요.', 'Use the review process tied to a real transaction or project. Unpublished reviews are kept separate from public feedback; signing up alone does not create a verified-transaction review.\n\nSeparate facts from opinions and avoid personal data, discriminatory or retaliatory content. Raise disputes with operations, identifying the project and concern.'), '리뷰|평가 작성|review|đánh giá nhau'),
    article('passport', 'projects', copy('Work Passport에는 무엇이 남나요?', 'What goes into a Work Passport?'), copy('플랫폼 안에서 실제로 수행하고 확인된 프로젝트·결과물·평가 기록을 경력 근거로 연결하는 기능입니다. 프로필 자기소개나 AI 점수만으로 검증된 수행경력이 만들어지지는 않습니다.\n\n기록이 없으면 경력·점수를 임의로 채우지 않습니다. 누락이나 사실관계 정정은 해당 프로젝트 근거와 함께 운영팀에 요청하세요.', 'Work Passport connects actual, confirmed project work, deliverables and feedback as evidence of experience. A self-description or AI score alone does not create verified work history.\n\nMissing history is not filled with invented experience or scores. Ask operations to correct omissions with evidence from the relevant project.'), 'passport|경력 인증|경력인증|hộ chiếu'),
    article('contact-privacy', 'policy', copy('인재의 연락처가 왜 보이지 않나요?', 'Why are talent contact details hidden?'), copy('계약 전 무단 접촉과 플랫폼 밖 거래를 줄이기 위해 이름·개인 이메일·전화번호 등 직접 식별정보를 제한합니다. 기업은 공개가 허용된 직무·역량·경력 근거부터 확인합니다.\n\n연락처 공개는 소개·계약 등 정해진 단계와 권한을 따릅니다. 챗봇은 다른 이용자의 연락처나 비공개 문서를 제공하지 않습니다.', 'Direct identifiers such as full names, personal emails and phone numbers are restricted before the appropriate introduction and contract steps. Companies first see permitted role, skill and experience information.\n\nDisclosure depends on the workflow stage and authorization. This chatbot never provides another user’s contacts or private documents.'), '연락처|개인 이메일|전화번호|contact details|private data|liên hệ bị ẩn'),
    article('direct-hire', 'policy', copy('프로젝트 후 직접 채용하고 싶어요', 'Can we hire someone after a project?'), copy('채용전환·소개 요청 절차를 이용하고 운영팀에 채용 조건을 전달하세요. 소개 이력, 예외 여부, 실제 적용 수수료와 계약 조건을 확인해야 합니다.\n\n기간·수수료·할인·대체보증은 체결된 약정이 우선하며 챗봇이 새 조건을 약속할 수 없습니다. 플랫폼 밖 우회계약으로 신고 절차를 생략하지 마세요.', 'Use the hiring-conversion or introduction process and share the proposed employment terms with operations. Introduction history, exceptions, applicable fees and contract terms need review.\n\nThe signed agreement governs periods, fees, discounts and replacement terms. This chatbot cannot offer new terms. Do not bypass the reporting process through an off-platform arrangement.'), '직접 채용|직접채용|전환수수료|direct hire|conversion|tuyển trực tiếp'),
    article('visa', 'policy', copy('E-7·D 비자가 보장되나요?', 'Is an E-7 or D visa guaranteed?'), copy('아니요. 직무·전공 관련 사전 점검은 최종 비자 심사나 법률 자문이 아닙니다. 비자 종류별 요건, 학력·경력, 고용 조건, 기업 요건은 출입국 전문가의 최종 검토가 필요합니다.\n\n공고 지원, AI 점수, 특정 대학 재학, 직무 선택만으로 한국 취업이나 입국 자격이 보장되지 않습니다. 비용과 서류도 운영팀·전문가에게 별도로 확인하세요.', 'No. A preliminary role or degree check is not a visa decision or legal advice. Visa-specific requirements, education, experience, employment terms and employer eligibility require final review by a qualified immigration professional.\n\nAn application, AI score, university enrolment or selected role does not guarantee permission to work or enter Korea. Confirm documents and any costs separately.'), '비자|e-7|e7|d-2|d-10|visa|입국'),
    article('payments', 'policy', copy('결제·에스크로·전자서명을 지금 사용할 수 있나요?', 'Are payments, escrow and e-signatures available?'), copy('결제·에스크로·전자서명은 공급자 계약과 운영 설정이 완료된 기능만 사용할 수 있습니다. 메뉴나 안내가 있다는 이유로 실결제·에스크로 보호가 활성화됐다고 보시면 안 됩니다.\n\n현재 이용 가능한 방식은 해당 화면의 상태와 운영팀 확인을 기준으로 판단하세요. 이 챗봇은 계좌를 새로 안내하거나 입금·정산·전자서명 완료를 확정하지 않습니다.', 'Payments, escrow and e-signatures can be used only when the relevant provider agreement and configuration are complete. A menu or description does not mean live payment or escrow protection is active.\n\nCheck the feature’s current screen and confirm with operations. This chatbot does not introduce bank details or confirm a payment, payout or signature.'), '결제|에스크로|전자서명|payment|escrow|signature|payout|thanh toán|ký quỹ'),
    article('refunds', 'policy', copy('환불·대체인재·분쟁은 어떻게 요청하나요?', 'How do I request a refund, replacement or dispute review?'), copy('해당 프로젝트의 약정과 실제 진행 기록을 기준으로 운영팀에 요청합니다. 프로젝트명, 발생한 문제, 합의 내용과 결과물 기록을 정리해 주세요. 민감한 자료는 챗봇에 입력하지 마세요.\n\n환불액·처리 기한·대체인재 제공 여부는 검토가 필요합니다. 챗봇이 환불이나 보상을 승인하거나 일률적인 보증을 약속하지 않습니다.', 'Contact operations using the project agreement and actual work records. Identify the project, issue, agreed terms and deliverable evidence. Do not put sensitive materials in this chatbot.\n\nRefund amounts, timelines and replacement availability require review. This chatbot cannot approve compensation or promise a blanket guarantee.'), '환불|분쟁|대체인재|refund|dispute|replacement|hoàn tiền|tranh chấp'),
    article('earlybird', 'policy', copy('얼리버드 혜택을 지금 받을 수 있나요?', 'Can I still claim early-bird benefits?'), copy('8월 5일 마감으로 안내했던 얼리버드 캠페인은 신규 신청 기간이 종료되었습니다. 과거 할인·노출·수수료 페이백 문구만으로 현재 혜택이 새로 부여되지는 않습니다.\n\n이미 자격을 충족한 계정의 혜택 적용 여부는 실제 기록과 확정 조건을 운영팀이 확인해야 합니다. 현재 모집 안내와 별도 혜택이 있는지는 운영팀에 문의해 주세요.', 'The early-bird campaign advertised with an August 5 deadline is closed to new claims. Old discount, placement or fee-rebate descriptions do not grant new benefits now.\n\nOperations must check existing eligibility against actual records and confirmed terms. Ask about the current cohort and any separate offers.'), '얼리버드|early bird|earlybird|할인|혜택|페이백|discount|ưu đãi'),
    article('privacy', 'policy', copy('개인정보·계정 삭제를 요청하고 싶어요', 'How do I request a data correction or account deletion?'), copy('수정 가능한 프로필 정보는 마이페이지에서 직접 변경하세요. 계정 삭제, 이메일 변경, 비공개 기록 정정 등 직접 처리할 수 없는 요청은 가입 이메일로 운영팀에 문의해 주세요. 본인 확인이 필요할 수 있습니다.\n\n거래·분쟁·법적 보관 의무에 따라 모든 기록이 즉시 삭제되는 것은 아닙니다. 정확한 범위와 일정은 개별 확인이 필요하며 챗봇은 삭제를 실행하지 않습니다.', 'Edit supported profile fields in your profile. For deletion, email changes or corrections you cannot make yourself, contact operations from your registered email; identity checks may be required.\n\nTransaction, dispute or legal retention requirements can prevent immediate deletion of every record. Scope and timing require case review. This chatbot cannot delete accounts.'), '개인정보|탈퇴|계정 삭제|정보 수정|privacy|delete account|change email|xóa tài khoản'),
    article('language', 'start', copy('한국어·영어·베트남어로 이용할 수 있나요?', 'Which languages can I use?'), copy('언어 선택에서 한국어, English, Tiếng Việt를 선택할 수 있습니다. 이 도움말도 선택한 언어로 표시됩니다. 기업이나 이용자가 직접 작성한 공고·메시지의 원문 언어는 다를 수 있습니다.\n\n자동 번역이나 AI 표현이 부정확하면 원문과 함께 확인하세요. 계약·비자·지급 조건은 번역문만으로 확정하지 마세요.', 'Choose 한국어, English or Tiếng Việt in the language selector. This help centre follows your selection. Listings and messages written by users may use another language.\n\nCheck the original when automatic translation or AI wording is unclear. Do not finalize contract, visa or payment terms solely from a translation.'), '언어|영어|베트남어|한국어|language|english|vietnamese|ngôn ngữ'),
    article('cohort', 'start', copy('현재 모집 규모는 어느 정도인가요?', 'How large is the initial cohort?'), copy('초기에는 약 10명 규모의 인재와 실제 기업 프로젝트를 중심으로 운영을 검증한 뒤 모집을 넓혀가는 방향입니다. 이는 계획 규모이며 현재 가입자 수나 남은 자리 수를 의미하지 않습니다.\n\n챗봇은 실시간 인원·자리 수·매칭 소요기간을 추정해서 알려주지 않습니다. 참여 가능 여부는 운영팀에 확인해 주세요.', 'The initial plan is to work with around ten talent participants and real company projects, validate operations, then expand. This is a planned cohort size—not a live member count or number of remaining places.\n\nThe chatbot does not estimate live capacity or matching times. Confirm current participation availability with operations.'), '10명|모집 규모|cohort|initial cohort|remaining places|đợt đầu'),
    article('support', 'policy', copy('운영팀에 문의하려면 어떻게 하나요?', 'How can I contact the operations team?'), copy('konexa.corp@gmail.com으로 문의해 주세요. 사용한 기능, 발생 시각, 오류 문구, 민감한 정보를 가린 화면을 함께 보내면 확인에 도움이 됩니다. 개인 계정 확인이 필요하면 가입 이메일에서 연락하세요.\n\n비밀번호·인증코드·API 키·주민등록번호는 보내지 마세요. 이 챗봇의 답변이나 이메일 링크 클릭만으로 문의가 자동 접수되는 것은 아닙니다. 메일 앱에서 직접 전송해야 합니다.', 'Email konexa.corp@gmail.com. Include the feature, time, error text and a screenshot with sensitive details hidden. Use your registered email for account-specific requests.\n\nNever send passwords, verification codes, API keys or identity numbers. A chatbot reply or clicking the email link does not submit a ticket automatically—you must send the email from your mail app.'), '고객센터|문의|사람 연결|운영팀|support|contact support|human|hỗ trợ'),
];
export function normalizeSupportText(value: string) {
    return value.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^\p{L}\p{N}]+/gu, ' ').replace(/\s+/g, ' ').trim();
}
export function findSupportArticles(question: string) {
    const normalized = normalizeSupportText(question);
    return SUPPORT_ARTICLES.map(entry => {
        const exactTitle = Object.values(entry.title).some(title => normalizeSupportText(title) === normalized);
        const matched = entry.keywords.filter(term => {
            const token = normalizeSupportText(term);
            if (/^[a-z0-9 ]+$/.test(token))
                return (` ${normalized} `).includes(` ${token} `);
            return normalized.includes(token);
        });
        return { article: entry, score: exactTitle ? 100 : matched.reduce((sum, term) => sum + (/^(konexa|코넥사)$/i.test(term) ? 2 : Math.max(8, Math.min(term.length, 16))), 0) };
    }).filter(item => item.score > 0).sort((a, b) => b.score - a.score).slice(0, 3);
}
export function safeSupportIds(value: unknown) {
    return Array.isArray(value) ? [...new Set(value.filter((id): id is string => typeof id === 'string' && SUPPORT_ARTICLES.some(entry => entry.id === id)))].slice(0, 3) : [];
}
export function supportArticleView(id: string, locale: SupportLocale) {
    const entry = SUPPORT_ARTICLES.find(item => item.id === id);
    return entry ? { id: entry.id, category: entry.category, title: entry.title[locale], answer: entry.answer[locale] } : null;
}
export const SUPPORT_FALLBACK = copy('확인된 도움말에서 이 질문의 답을 찾지 못했습니다. 아래 주제를 선택하거나 운영팀에 문의해 주세요. 확인되지 않은 정책이나 개인 계정 상태는 추측하지 않겠습니다.', 'I could not find a confirmed answer in our help guidance. Choose a topic below or contact operations. I will not guess about policies or private account status.');
